saveExact: true
engineStrict: true
minimumReleaseAge: 1440
minimumReleaseAgeExcludePrune: true
trustPolicy: "no-downgrade"
trustPolicyExcludePrune: true
allowBuilds:
  '@vscode/vsce-sign': true
  keytar: true
