saveExact: true
engineStrict: true
minimumReleaseAge: 1440
minimumReleaseAgeExcludePrune: true
trustPolicy: "no-downgrade"
trustPolicyExclude:
  - semver@5.7.2
allowBuilds:
  "@vscode/vsce-sign": true
  keytar: true
